[package]
name = "lmutib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
git2 = "0.14.2"
flate2 = "1.0.23"
